version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "k8s.io/*" # manually handle k8s bumps
    - dependency-name: "knative.dev/*" # knobots handles knative bumps
